// About: sections copied from README.md at request time (the README is generated by scripts/make_readme.py), never retyped here.
import { h, clear } from "/ui/dom.js";
import { alertBox, emptyState, errorState, pageHead, renderMarkdown, skeletonCards } from "/ui/components.js";
import { get } from "/ui/api.js";
import { session } from "/ui/store.js";

export default async function about({ container }) {
  container.append(pageHead("About and data", "Data credits and licence, the gated-data notice, how AI was used, and the limitations. These sections are read from the README that the project generates."));
  const body = h("div", { class: "stack" }, skeletonCards(2)); container.append(body);
  try {
    const r = await get("/api/public/about");
    clear(body);
    if (!r.available) return body.append(h("div", { class: "card" }, emptyState("README not found", "Run python scripts/make_readme.py to generate it.", { icon: "info" })));
    const S = r.sections;
    body.append(alertBox("Sign-in in this app separates what each role sees. It is not access control for the dataset: IL-PCSR is gated and for research use only, and its terms apply regardless.", "", "lock"),
      ...["Gated data notice", "Data credits and licences", "Limitations", "AI use", "Related work"].filter((t) => S[t]).map((t) => h("section", { class: "card stack" }, h("h2", {}, t === "Gated data notice" ? "Gated data" : t), renderMarkdown(S[t]))),
      h("section", { class: "card stack" }, h("h2", {}, "This server"), h("p", { class: "small" }, `Data mode: ${session.mode}. Case text and titles are ${session.show_text ? "shown (SHOW_TEXT=1)" : "hidden"}. Saved searches and history keep ids and settings only.`)));
  } catch (e) { clear(body).append(errorState(e)); }
}
