// Living style guide: every component, shown in the light and the dark theme at the same time.
import { h, clear } from "/ui/dom.js";
import { icon } from "/ui/icons.js";
import { ZONES, alertBox, badge, button, chip, combobox, courtBadge, dualRange, emptyState, errorState, field, hbar, kpi, legend, modal, pageHead, scoreRing, segmented, skeleton, stackBar, table, tabs, toast, zoneChip, zoneLabel, drawer, FEATURE_LABEL } from "/ui/components.js";
import { barsCI, lines, pairedBars } from "/ui/charts.js";

const swatch = (name, v) => h("div", { class: "swatch" }, h("i", { style: { background: `var(${v})` } }), h("span", {}, v));
function demo() {
  const sample = [{ label: "tf-idf", value: 0.122, lo: 0.11, hi: 0.134 }, { label: "Config A", value: 0.206, lo: 0.19, hi: 0.222, color: "var(--f-neighbour)" }];
  return h("div", { class: "stack", style: { gap: "var(--s-5)" } },
    h("section", {}, h("h3", {}, "Colour"), h("div", { class: "swatches" }, ["--bg", "--surface", "--surface-2", "--text", "--muted", "--border", "--brand", "--ok", "--warn", "--err", "--info", "--role-researcher", "--role-analyst", "--role-admin"].map((v) => swatch(v, v)))),
    h("section", {}, h("h3", {}, "Zone palette (identical in every chart, chip and bar)"), h("div", { class: "row" }, ZONES.map(zoneChip)), h("div", { class: "swatches" }, ZONES.map((z) => swatch(zoneLabel(z), `--z-${z}`)))),
    h("section", {}, h("h3", {}, "Score components"), h("div", { class: "row" }, legend(["text", "neighbour", "authority", "recency", "court"])), stackBar([{ key: "text", value: 0.35 }, { key: "neighbour", value: 0.49 }, { key: "authority", value: 0.16 }])),
    h("section", {}, h("h3", {}, "Type scale"), h("div", { class: "stack", style: { gap: "4px" } }, [["--t-2xl", "Display 34"], ["--t-xl", "Heading 26"], ["--t-lg", "Title 20"], ["--t-md", "Lead 17"], ["--t-base", "Body 15: the quick brown fox jumps over the lazy dog"], ["--t-sm", "Small 13"], ["--t-xs", "Caption 12"]].map(([v, t]) => h("div", { style: { fontSize: `var(${v})`, fontWeight: v.includes("xl") ? 650 : 400 } }, t)), h("div", { class: "mono" }, "Mono: doc 4375213 · IPC_302 · 0.2087"))),
    h("section", {}, h("h3", {}, "Buttons"), h("div", { class: "row" }, button("Primary"), button("Secondary", { variant: "secondary" }), button("Ghost", { variant: "ghost" }), button("Danger", { variant: "danger" }), button("With icon", { icon: "search" }), button("Loading", { loading: true }), button("Disabled", { disabled: true }), button("", { icon: "settings", variant: "secondary", title: "Icon button" }), button("Small", { size: "sm", variant: "secondary" }), button("Large", { size: "lg" }))),
    h("section", {}, h("h3", {}, "Inputs"), h("div", { class: "grid cols-2" }, field("Text input", h("input", { class: "input", placeholder: "Placeholder" }), { hint: "Hint text" }), field("With error", h("input", { class: "input", value: "oops", "aria-invalid": "true" }), { error: "This field is required." }),
      field("Select", h("select", { class: "select" }, h("option", {}, "tf-idf"), h("option", {}, "BM25"))), field("Textarea", h("textarea", { class: "textarea", placeholder: "Facts and issues" })),
      h("div", { class: "stack" }, h("label", { class: "check" }, h("input", { type: "checkbox", checked: true }), "Checkbox"), h("label", { class: "switch" }, h("input", { type: "checkbox", checked: true }), "Switch"), h("input", { class: "range", type: "range", "aria-label": "Slider" }), dualRange({ min: 1950, max: 2020, lo: 1980, hi: 2005, label: "Years" })),
      h("div", { class: "stack" }, combobox({ items: [{ value: "a", label: "Q-TE1", meta: "SC · 2001" }, { value: "b", label: "Q-TE2", meta: "HC · 2010" }], value: "a", label: "Combobox" }), segmented([{ value: "1", label: "tf-idf" }, { value: "2", label: "BM25" }, { value: "3", label: "Ours" }], "3", () => {}, { label: "Segmented" })))),
    h("section", {}, h("h3", {}, "Chips and badges"), h("div", { class: "row" }, chip("Chip"), chip("Pressed", { pressed: true, onClick: () => {} }), chip("Removable", { onRemove: () => {} }), chip("IPC_302", { mono: true }), badge("ok", "ok"), badge("warning", "warn"), badge("error", "err"), badge("info", "info"), badge("brand", "brand"), courtBadge("SC"), courtBadge("HC"), courtBadge("OTHER"), h("kbd", {}, "⌘ K"))),
    h("section", {}, h("h3", {}, "Cards, KPI and score ring"), h("div", { class: "grid cols-3" }, kpi("MAP", 0.2087, { decimals: 3, hint: "example number" }), h("div", { class: "card tight row" }, scoreRing(0.82), h("span", { class: "small" }, "Score ring")), h("div", { class: "card tight stack" }, hbar("Facts", 12, 20, { color: "var(--z-facts)", text: "12" }), hbar("Reasoning", 18, 20, { color: "var(--z-reasoning)", text: "18" })))),
    h("section", {}, h("h3", {}, "Table and tabs"), tabs([{ id: "a", label: "Dev" }, { id: "b", label: "Test" }], "a", () => {}), table(["System", "MAP", "R@10"], [["tf-idf", "0.1220", "0.1804"], ["Config A", "0.2063", "0.2844"]], { numeric: [1, 2], highlight: (i) => i === 1 })),
    h("section", {}, h("h3", {}, "Charts (hand-written SVG)"), barsCI(sample, { width: 560, left: 90, rowH: 32 }), pairedBars([{ label: "No leave-one-out", before: 0.268, after: 0.874 }], { width: 560, left: 140 })),
    h("section", {}, h("h3", {}, "Feedback"), h("div", { class: "stack" }, alertBox("Information message.", ""), alertBox("Warning message.", "warn", "alert"), alertBox("Error message.", "err", "alert"), alertBox("Success message.", "ok", "check"), h("div", { class: "row" }, skeleton("30%", "16px"), skeleton("50%", "16px")), emptyState("Nothing here yet", "An empty state explains what will appear and how to get started.", { icon: "bookmark" }), errorState(new Error("Example error message"), () => {}))));
}

export default async function styleguide({ container }) {
  container.append(pageHead("Style guide", "Components and tokens from tokens.css and components.css, in both themes at once. Colours, type, spacing, radii, shadows and motion are defined once in tokens.css."));
  const overlays = h("div", { class: "card row" }, h("b", {}, "Overlays"), button("Modal", { variant: "secondary", onClick: () => modal({ title: "Modal", body: h("p", {}, "Focus is trapped here. Esc closes it.") }) }), button("Drawer", { variant: "secondary", onClick: () => drawer({ title: "Drawer", body: h("p", {}, "Slides in from the right.") }) }),
    button("Toast", { variant: "secondary", onClick: () => toast("A short confirmation.", "ok") }), button("Error toast", { variant: "secondary", onClick: () => toast("Something failed.", "err") }), h("span", { class: "small muted", "data-tip": "Tooltip text appears on hover and keyboard focus." }, "Hover or focus for a tooltip"));
  container.append(overlays, h("div", { class: "grid cols-2", style: { alignItems: "start" } }, h("div", { class: "theme-box", "data-theme": "light" }, h("h2", { style: { marginBottom: "var(--s-4)" } }, "Light"), demo()), h("div", { class: "theme-box", "data-theme": "dark" }, h("h2", { style: { marginBottom: "var(--s-4)" } }, "Dark"), demo())));
}
