"""Figures (docs/figures/*.png) and tables (docs/results_tables.md) from saved runs in results/. Aggregates only.

Reads dev_eval.json, test_eval.json (if the final run exists), b2_ablation_dev.json, leakage_audit.json,
efficiency.json, zone_matrix.json, bm25_tuning.json, w_variant.json. Usage: python scripts/make_report_assets.py
"""
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
R, FIG = ROOT / "results", ROOT / "docs" / "figures"
FIG.mkdir(parents=True, exist_ok=True)


def load(n):
    p = R / n
    return json.loads(p.read_text()) if p.exists() else None


dev, test, abl, leak, eff, zm, bm, wv = (load(n) for n in ("dev_eval.json", "test_eval.json", "b2_ablation_dev.json", "leakage_audit.json",
                                                            "efficiency.json", "zone_matrix.json", "bm25_tuning.json", "w_variant.json"))
KEYS = ["MAP", "MRR", "nDCG@10", "nDCG@20", "R@5", "R@10", "R@20", "P@10"]
md = ["# Results tables", "", "Generated by `scripts/make_report_assets.py` from saved runs in `results/`. Aggregates only.",
      "Headline comparisons use Facts+Issues queries (D16); rows marked REFERENCE use the full judgment and are not comparable.", ""]
f = lambda x: "–" if x is None else f"{x:.4f}"
ci = lambda d: f"{d[0]:+.4f} [{d[1]:+.4f}, {d[2]:+.4f}]"


def run_tables(run, title):
    out = [f"## {title}", "", f"{run['n_queries']} queries; candidates = pool ({run['candidates']}); run `{run['run_id']}`; "
           f"neighbour k={run['neighbour']['k']}, p={run['neighbour']['p']}; Config A weights {run['config_a']}.", "",
           "| ranker | " + " | ".join(KEYS) + " |", "|---|" + "---|" * len(KEYS)]
    out += [f"| {n} | " + " | ".join(f(m[k]) for k in KEYS) + " |" for n, m in run["macro"].items()]
    out += ["", "Paired bootstrap (1000 resamples), difference to tf-idf: mean [95% interval].", "",
            "| ranker | MAP | MRR | nDCG@10 | R@10 | R@20 |", "|---|---|---|---|---|---|"]
    for n, d in run["bootstrap_diff_[mean,lo95,hi95]"]["vs_tfidf"].items():
        out.append(f"| {n} | " + " | ".join(ci(d[k]) for k in ("MAP", "MRR", "nDCG@10", "R@10", "R@20")) + " |")
    for key, label in (("ConfigA_vs_BM25_tuned", "Config A minus tuned BM25"), ("ConfigA_temporal_vs_ConfigA", "Config A + temporal filter minus Config A")):
        d = run["bootstrap_diff_[mean,lo95,hi95]"][key]
        out.append(f"| **{label}** | " + " | ".join(ci(d[k]) for k in ("MAP", "MRR", "nDCG@10", "R@10", "R@20")) + " |")
    out += ["", "Micro-averaged (pooled over queries):", "", "| ranker | " + " | ".join(next(iter(run["micro"].values())).keys()) + " |",
            "|---|" + "---|" * len(next(iter(run["micro"].values())))]
    out += [f"| {n} | " + " | ".join(f(v) for v in m.values()) + " |" for n, m in run["micro"].items()]
    n = run["notes"]
    out += ["", f"Temporal filter: both dates known for {n['share_pairs_both_dates_known']:.1%} of query-document pairs; "
            f"{n['share_relevant_pairs_removed_by_filter']:.1%} of relevant pairs with both dates are removed by the filter (the relevant precedent is not strictly earlier). "
            f"First-stage recall@1000: {n['first_stage_recall_at_1000']:.4f}.", ""]
    return out


if dev:
    md += run_tables(dev, "Dev run")
if test:
    md += run_tables(test, "Test run (final, run once with --final)")
else:
    md += ["## Test run", "", "PLACEHOLDER: the final test run has not been executed (`python -m irlegal.evaluation.runner --split test --final`).", ""]
if bm:
    d, t = bm["default"], bm["tuned"]
    md += ["## BM25 tuning (dev, Facts+Issues queries)", "", "| doc zone | setting | k1 | b | qtf | MAP | R@10 |", "|---|---|---|---|---|---|---|"]
    for z in ("all", "fi"):
        md += [f"| {z} | default | {d[z]['k1']} | {d[z]['b']} | {d[z]['qtf']} | {f(d[z]['MAP'])} | {f(d[z]['R@10'])} |",
               f"| {z} | tuned | {t[z]['k1']} | {t[z]['b']} | {t[z]['qtf']} | {f(t[z]['MAP'])} | {f(t[z]['R@10'])} |"]
    md.append("")
if abl:
    md += ["## Ablation ladder (dev)", "", "| row | MAP | MRR | nDCG@10 | R@10 | R@20 | MAP diff to tf-idf |", "|---|---|---|---|---|---|---|"]
    for n, r in abl["rows"].items():
        md.append(f"| {n} | {f(r['MAP'])} | {f(r['MRR'])} | {f(r['nDCG@10'])} | {f(r['R@10'])} | {f(r['R@20'])} | {ci(abl['diff_vs_tfidf_[mean,lo95,hi95]'][n]['MAP'])} |")
    md += ["", "Union first-stage recall (dev): " + json.dumps(abl["union_recall"]), ""]
if wv:
    md += ["## Regularised zone-pair variant (D18, dev)", "", f"Cross-validated stopping sweep: {wv['chosen_sweep']}. Survives the D18 criterion: **{wv['survives_D18_criterion']}**.", "",
           "| metric | tf-idf | variant | diff [95% interval] |", "|---|---|---|---|"]
    md += [f"| {k} | {f(v['tfidf'])} | {f(v['variant'])} | {ci([v['diff'], *v['ci95']])} |" for k, v in wv["dev"].items()]
    md.append("")
if leak:
    md += ["## Leakage audit", "", "| audit | system | metric | delta [95% interval] |", "|---|---|---|---|"]
    for a, body in leak.items():
        if isinstance(body, dict):
            for s, v in body.items():
                if isinstance(v, dict):
                    k = next((x for x in v if "[mean" in x), None)
                    if k:
                        md += [f"| {a} | {s} | {m} | {ci(v[k][m])} |" for m in ("MAP", "R@10")]
    md.append("")
if eff:
    md += ["## Efficiency (dev; latency is machine dependent)", "", "| method | median ms | p95 ms | candidates | MAP | MAP kept | R@10 kept |", "|---|---|---|---|---|---|---|"]
    md += [f"| {x['method']} | {x['median_ms']} | {x['p95_ms']} | {x['mean_candidates_scored']} | {f(x['MAP'])} | {f(x['MAP_retained'])} | {f(x['R@10_retained'])} |"
           for x in eff["text_stage"] + eff["cluster_pruning"]]
    md += ["", "| K | method | median ms | p95 ms |", "|---|---|---|---|"] + [f"| {x['K']} | {x['method']} | {x['median_ms']} | {x['p95_ms']} |" for x in eff["heap_vs_sort"]] + [""]
crawl, dec, andb = load("crawl_sim.json"), load("decompose_dev.json"), load("and_benchmark.json")
if dec:
    md += ["## Issue decomposition (dev, N6)", "", f"{dec['queries_with_two_or_more_issue_sub_queries']} of {dec['n_queries']} queries yield two or more sub-queries; mean {dec['mean_sub_queries_per_query']} per query.", "",
           "| system | MAP | MRR | nDCG@10 | R@10 | MAP diff to single query |", "|---|---|---|---|---|---|"]
    for n, r in dec["rows"].items():
        a = r["all_queries"]
        md.append(f"| {n} | {f(a['MAP'])} | {f(a['MRR'])} | {f(a['nDCG@10'])} | {f(a['R@10'])} | {ci(r['MAP_diff_vs_single_[mean,lo95,hi95]']) if 'MAP_diff_vs_single_[mean,lo95,hi95]' in r else '–'} |")
    md.append("")
if crawl:
    bs = list(next(iter(crawl["share_of_targets_fetched_by_budget"].values())))
    md += ["## Crawl simulation (N5; simulation only)", "", crawl["targets"] + f"; {crawl['trials']} trials, {crawl['seeds_per_trial']} seeds each; {crawl['hosts']} simulated hosts.", "",
           "| crawler | " + " | ".join(f"after {b} fetches" for b in bs) + " |", "|---|" + "---|" * len(bs)]
    md += [f"| {n} | " + " | ".join(f"{v[b]:.3f}" for b in bs) + " |" for n, v in crawl["share_of_targets_fetched_by_budget"].items()] + [""]
if andb:
    md += ["## AND processing order (real index)", "", f"{andb['queries']} random 3-5 word queries.", "", "| order | comparisons | seconds |", "|---|---|---|"]
    md += [f"| {k} | {andb[k]['comparisons']:,} | {andb[k]['seconds']} |" for k in ("input_order", "df_order")] + [""]
(ROOT / "docs" / "results_tables.md").write_text("\n".join(md))

# ------------------------------------------------------------------ figures
def barci(labels, vals, lo, hi, title, fname, xlabel, colors=None):
    fig, ax = plt.subplots(figsize=(9, 0.45 * len(labels) + 1.2))
    y = np.arange(len(labels))
    ax.barh(y, vals, color=colors or "#3b6ea8", alpha=.85)
    ax.errorbar(vals, y, xerr=[np.array(vals) - np.array(lo), np.array(hi) - np.array(vals)], fmt="none", ecolor="black", capsize=3)
    ax.set_yticks(y); ax.set_yticklabels(labels, fontsize=8); ax.invert_yaxis(); ax.axvline(0, color="grey", lw=.8)
    ax.set_xlabel(xlabel); ax.set_title(title, fontsize=10); fig.tight_layout(); fig.savefig(FIG / fname, dpi=150); plt.close(fig)


for run, tag in ((dev, "dev"), (test, "test")):
    if not run:
        continue
    fig, ax = plt.subplots(figsize=(6.5, 4.2))
    x = np.linspace(0, 1, 11)
    for n, y in run["pr_curve_11pt"].items():
        if n.startswith("REFERENCE") or n == "random":
            continue
        ax.plot(x, y, marker="o", ms=3, label=n)
    ax.set_xlabel("recall"); ax.set_ylabel("interpolated precision"); ax.set_title(f"Interpolated PR curve ({tag}, Facts+Issues queries)", fontsize=10)
    ax.legend(fontsize=7); ax.set_ylim(0, None); fig.tight_layout(); fig.savefig(FIG / f"pr_curve_{tag}.png", dpi=150); plt.close(fig)
if abl:
    rows = [(n, m) for n, m in abl["rows"].items() if not n.startswith(("REFERENCE", "ref:"))]
    vals = [m["MAP"] for _, m in rows]
    cis = [abl["diff_vs_tfidf_[mean,lo95,hi95]"][n]["MAP"] for n, _ in rows]
    barci([n for n, _ in rows], vals, [v - d[0] + d[1] for v, d in zip(vals, cis)], [v - d[0] + d[2] for v, d in zip(vals, cis)],
          "Ablation ladder, dev MAP (bars: interval of the paired difference to tf-idf, centred on the row)", "ablation_dev.png", "MAP")
if leak:
    items = []
    for a, body in leak.items():
        if isinstance(body, dict):
            for s, v in body.items():
                if isinstance(v, dict):
                    k = next((x for x in v if "[mean" in x), None)
                    if k and s in ("config_A", "neighbour_alone", "authority_alone", "tfidf"):
                        items.append((f"{a[:1]}: {s}", v[k]["MAP"]))
    barci([i[0] for i in items], [i[1][0] for i in items], [i[1][1] for i in items], [i[1][2] for i in items],
          "Leakage audit: change in MAP when the leak is allowed (a, b, c) or the filter is on (d)", "leakage_audit.png", "delta MAP",
          colors=["#b4566a" if i[0].startswith("a") else "#c08a2b" if i[0].startswith("b") else "#3f8f7a" for i in items])
if eff:
    fig, ax = plt.subplots(figsize=(7.5, 4.6))
    fams = sorted({x["family"] for x in eff["text_stage"] + eff["cluster_pruning"]})
    for i, fam in enumerate(fams):
        pts = [x for x in eff["text_stage"] + eff["cluster_pruning"] if x["family"] == fam and "alone" not in x["method"]]
        ax.scatter([p["mean_candidates_scored"] for p in pts], [p["MAP_retained"] for p in pts], label=fam, s=28)
    ax.set_xscale("log"); ax.set_xlabel("mean candidates scored (log)"); ax.set_ylabel("MAP retained vs exhaustive"); ax.set_ylim(0, 1.05)
    ax.axhline(1, color="grey", lw=.6); ax.legend(fontsize=8); ax.set_title("Efficiency vs effectiveness (dev)", fontsize=10)
    fig.tight_layout(); fig.savefig(FIG / "efficiency_curve.png", dpi=150); plt.close(fig)
if zm:
    fig, axes = plt.subplots(1, 2, figsize=(12, 3.2))
    for ax, key, ttl in ((axes[0], "W", "saved W (dev early stopping: baseline)"), (axes[1], "W_last_sweep_not_selected", "fully trained W (not selected)")):
        W = zm.get(key)
        if not W:
            continue
        M = np.array([[W[r][c] for c in zm["cols_pool_zone"]] for r in zm["rows_query_view"]])
        im = ax.imshow(M, cmap="Blues", vmin=0, vmax=max(M.max(), 1e-9))
        ax.set_xticks(range(len(zm["cols_pool_zone"]))); ax.set_xticklabels(zm["cols_pool_zone"], rotation=40, ha="right", fontsize=7)
        ax.set_yticks(range(len(zm["rows_query_view"]))); ax.set_yticklabels(zm["rows_query_view"], fontsize=8); ax.set_title(ttl, fontsize=9)
        for i in range(M.shape[0]):
            for j in range(M.shape[1]):
                ax.text(j, i, f"{M[i, j]:.2f}", ha="center", va="center", fontsize=6)
    fig.suptitle("Zone-pair weight matrix: NEGATIVE RESULT (did not beat tf-idf on dev)", fontsize=10)
    fig.tight_layout(); fig.savefig(FIG / "zone_matrix_negative_result.png", dpi=150); plt.close(fig)
print("wrote docs/results_tables.md and", sorted(p.name for p in FIG.glob("*.png")))
